//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chatapp/chat_app.proto

package proto.kotlin;

@kotlin.jvm.JvmSynthetic
inline fun chatMessageResponse(block: proto.kotlin.ChatMessageResponseKt.Dsl.() -> Unit): proto.kotlin.ChatMessageResponse =
  proto.kotlin.ChatMessageResponseKt.Dsl._create(proto.kotlin.ChatMessageResponse.newBuilder()).apply { block() }._build()
object ChatMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: proto.kotlin.ChatMessageResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: proto.kotlin.ChatMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): proto.kotlin.ChatMessageResponse = _builder.build()

    /**
     * <code>.proto.chat_app.ChatMessage chat_message = 1;</code>
     */
    var chatMessage: proto.kotlin.ChatMessage
      @JvmName("getChatMessage")
      get() = _builder.getChatMessage()
      @JvmName("setChatMessage")
      set(value) {
        _builder.setChatMessage(value)
      }
    /**
     * <code>.proto.chat_app.ChatMessage chat_message = 1;</code>
     */
    fun clearChatMessage() {
      _builder.clearChatMessage()
    }
    /**
     * <code>.proto.chat_app.ChatMessage chat_message = 1;</code>
     * @return Whether the chatMessage field is set.
     */
    fun hasChatMessage(): kotlin.Boolean {
      return _builder.hasChatMessage()
    }

    /**
     * <code>.proto.chat_app.ChatMessageResponse.MessageStatus msg_status = 2;</code>
     */
    var msgStatus: proto.kotlin.ChatMessageResponse.MessageStatus
      @JvmName("getMsgStatus")
      get() = _builder.getMsgStatus()
      @JvmName("setMsgStatus")
      set(value) {
        _builder.setMsgStatus(value)
      }
    /**
     * <code>.proto.chat_app.ChatMessageResponse.MessageStatus msg_status = 2;</code>
     */
    fun clearMsgStatus() {
      _builder.clearMsgStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun proto.kotlin.ChatMessageResponse.copy(block: proto.kotlin.ChatMessageResponseKt.Dsl.() -> Unit): proto.kotlin.ChatMessageResponse =
  proto.kotlin.ChatMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
