//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chatapp/chat_app.proto

package proto.kotlin;

@kotlin.jvm.JvmSynthetic
inline fun connectUserRequest(block: proto.kotlin.ConnectUserRequestKt.Dsl.() -> Unit): proto.kotlin.ConnectUserRequest =
  proto.kotlin.ConnectUserRequestKt.Dsl._create(proto.kotlin.ConnectUserRequest.newBuilder()).apply { block() }._build()
object ConnectUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: proto.kotlin.ConnectUserRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: proto.kotlin.ConnectUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): proto.kotlin.ConnectUserRequest = _builder.build()

    /**
     * <code>string user_id = 1;</code>
     */
    var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 1;</code>
     */
    fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string name = 2;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string device = 3;</code>
     */
    var device: kotlin.String
      @JvmName("getDevice")
      get() = _builder.getDevice()
      @JvmName("setDevice")
      set(value) {
        _builder.setDevice(value)
      }
    /**
     * <code>string device = 3;</code>
     */
    fun clearDevice() {
      _builder.clearDevice()
    }

    /**
     * <code>.proto.chat_app.ConnectUserRequest.Type type = 4;</code>
     */
    var type: proto.kotlin.ConnectUserRequest.Type
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.proto.chat_app.ConnectUserRequest.Type type = 4;</code>
     */
    fun clearType() {
      _builder.clearType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun proto.kotlin.ConnectUserRequest.copy(block: proto.kotlin.ConnectUserRequestKt.Dsl.() -> Unit): proto.kotlin.ConnectUserRequest =
  proto.kotlin.ConnectUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
