//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chatapp/chat_app.proto

package proto.kotlin;

@kotlin.jvm.JvmSynthetic
inline fun queryMessagesResponse(block: proto.kotlin.QueryMessagesResponseKt.Dsl.() -> Unit): proto.kotlin.QueryMessagesResponse =
  proto.kotlin.QueryMessagesResponseKt.Dsl._create(proto.kotlin.QueryMessagesResponse.newBuilder()).apply { block() }._build()
object QueryMessagesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: proto.kotlin.QueryMessagesResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: proto.kotlin.QueryMessagesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): proto.kotlin.QueryMessagesResponse = _builder.build()

    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     */
    var user1: proto.kotlin.User
      @JvmName("getUser1")
      get() = _builder.getUser1()
      @JvmName("setUser1")
      set(value) {
        _builder.setUser1(value)
      }
    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     */
    fun clearUser1() {
      _builder.clearUser1()
    }
    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     * @return Whether the user1 field is set.
     */
    fun hasUser1(): kotlin.Boolean {
      return _builder.hasUser1()
    }

    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     */
    var user2: proto.kotlin.User
      @JvmName("getUser2")
      get() = _builder.getUser2()
      @JvmName("setUser2")
      set(value) {
        _builder.setUser2(value)
      }
    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     */
    fun clearUser2() {
      _builder.clearUser2()
    }
    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     * @return Whether the user2 field is set.
     */
    fun hasUser2(): kotlin.Boolean {
      return _builder.hasUser2()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class MessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     */
     val messages: com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessagesList()
      )
    /**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessages")
    fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.add(value: proto.kotlin.ChatMessage) {
      _builder.addMessages(value)
    }/**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.plusAssign(value: proto.kotlin.ChatMessage) {
      add(value)
    }/**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessages")
    fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.addAll(values: kotlin.collections.Iterable<proto.kotlin.ChatMessage>) {
      _builder.addAllMessages(values)
    }/**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessages")
    inline operator fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.plusAssign(values: kotlin.collections.Iterable<proto.kotlin.ChatMessage>) {
      addAll(values)
    }/**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     * @param index The index to set the value at.
     * @param value The messages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessages")
    operator fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.set(index: kotlin.Int, value: proto.kotlin.ChatMessage) {
      _builder.setMessages(index, value)
    }/**
     * <code>repeated .proto.chat_app.ChatMessage messages = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessages")
    fun com.google.protobuf.kotlin.DslList<proto.kotlin.ChatMessage, MessagesProxy>.clear() {
      _builder.clearMessages()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun proto.kotlin.QueryMessagesResponse.copy(block: proto.kotlin.QueryMessagesResponseKt.Dsl.() -> Unit): proto.kotlin.QueryMessagesResponse =
  proto.kotlin.QueryMessagesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
