//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: chatapp/chat_app.proto

package proto.kotlin;

@kotlin.jvm.JvmSynthetic
inline fun queryMessagesRequest(block: proto.kotlin.QueryMessagesRequestKt.Dsl.() -> Unit): proto.kotlin.QueryMessagesRequest =
  proto.kotlin.QueryMessagesRequestKt.Dsl._create(proto.kotlin.QueryMessagesRequest.newBuilder()).apply { block() }._build()
object QueryMessagesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: proto.kotlin.QueryMessagesRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: proto.kotlin.QueryMessagesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): proto.kotlin.QueryMessagesRequest = _builder.build()

    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     */
    var user1: proto.kotlin.User
      @JvmName("getUser1")
      get() = _builder.getUser1()
      @JvmName("setUser1")
      set(value) {
        _builder.setUser1(value)
      }
    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     */
    fun clearUser1() {
      _builder.clearUser1()
    }
    /**
     * <code>.proto.chat_app.User user1 = 1;</code>
     * @return Whether the user1 field is set.
     */
    fun hasUser1(): kotlin.Boolean {
      return _builder.hasUser1()
    }

    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     */
    var user2: proto.kotlin.User
      @JvmName("getUser2")
      get() = _builder.getUser2()
      @JvmName("setUser2")
      set(value) {
        _builder.setUser2(value)
      }
    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     */
    fun clearUser2() {
      _builder.clearUser2()
    }
    /**
     * <code>.proto.chat_app.User user2 = 2;</code>
     * @return Whether the user2 field is set.
     */
    fun hasUser2(): kotlin.Boolean {
      return _builder.hasUser2()
    }

    /**
     * <code>string time_constraint = 3;</code>
     */
    var timeConstraint: kotlin.String
      @JvmName("getTimeConstraint")
      get() = _builder.getTimeConstraint()
      @JvmName("setTimeConstraint")
      set(value) {
        _builder.setTimeConstraint(value)
      }
    /**
     * <code>string time_constraint = 3;</code>
     */
    fun clearTimeConstraint() {
      _builder.clearTimeConstraint()
    }

    /**
     * <code>int32 limit = 4;</code>
     */
    var limit: kotlin.Int
      @JvmName("getLimit")
      get() = _builder.getLimit()
      @JvmName("setLimit")
      set(value) {
        _builder.setLimit(value)
      }
    /**
     * <code>int32 limit = 4;</code>
     */
    fun clearLimit() {
      _builder.clearLimit()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun proto.kotlin.QueryMessagesRequest.copy(block: proto.kotlin.QueryMessagesRequestKt.Dsl.() -> Unit): proto.kotlin.QueryMessagesRequest =
  proto.kotlin.QueryMessagesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
